### PR TITLE
Milestone 2: Styling 

### PR DESCRIPTION
**Pull request by Bismarck-GM**
## Youtube Milestone 2:

In this milestone we:

- Changed the navbar to a flex layout. 
- Corrected the footer, styled buttons.
- Changed the sizes of the sidebar of the featured videos.
- Changed the space between the navbar and the main container.
- Edited and added a complete README file.
- Validated our Markup.
- Stylized icons and text to copy the ones of Youtube.

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Santiago Rodriguez & Gero Morisot Morla**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all congratulations on your first Microverse project!🌟**

Good job with the fixes from the last review, but next time remember to not close the pull request.
You don't need to open a new one, you can just do the needed changes, commit and push them, and then request a new code review with the same PR link.

There are some small issues to fix before going to the next project, but you guys got this!💪 

---------     

## Required Changes 🏗 👷‍♀ 

- [x] Make sure there are no errors or warnings on your [HTML validation.](https://validator.w3.org)

- [x] Don't use id selectors for styling, [read this article on why it's better to use classes](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4), make sure to change the id selectors to class selectors.

- [x] Remember to follow [commit writing best practices ](https://chris.beams.io/posts/git-commit/)from now on:
  - Write your commit messages using the imperative tense

- [x] Don't use a single image for the user icon, name, and subscribe button under the video.
Each element should be it's own.
- [x] Same as above for the Logo and hamburger icon. Make sure they are separated elements.

- [x] To the side of the search bar there should be three images, make sure you add one more.

- [x] [OPTIONAL] Instead of using screenshot images with a set background for the icons use actual icons, you can find them at sites like [fontawesome](fontawesome.com/), png images with a transparent background, or svg images.
[If you are not sure about the different kinds of images you can use read this article.](https://cheesecakelabs.com/blog/jpg-png-svg-web-beginners-guide/)
[If you want to know more about svgs, they are great for logos, read this one.](https://css-tricks.com/using-svg/)

When you get an image to use as an icon or logo you should always look for a png image with a transparent background or an svg one. You can also use icons like the ones you find at [fontawesome.](https://fontawesome.com)

When you look for logos you can either search the original site and get the transparent image/svg there or google it. Ex: 'youtube logo png transparent background'

----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by santiagorodriguezbermudez** [comment]
## Youtube Review 2:

In this review we:

- Validated the markup on the HTML for no errors/warnings.
- Changed the id and class composition.
- Added icons instead of images.
- Split the user icon, name, and subscribe button under the main video.
- Added the profile account icon.
- Added Youtube SVG logo plus hamburger menu icon. 
- Styled the navbar and space between elements
- Added lower border to the number of views

**Comment by trekab** [comment]
Hello @santiagorodriguezbermudez & @Bismarck-GM, well done on implementing the last requested changes. You have a few changes to make to complete this project. You're almost there! :wink: 

# Required Changes:
* The buttons in the main video section (Number of views, Subscribe, Share, and More) are not in their right positions.
* The font size is too big compared to the site being cloned.

__Kindly work on these change and submit a new code review request_
Happy coding!

**Comment by santiagorodriguezbermudez** [comment]
## Youtube Review 3:

In this review we:

- Changed the size of the font
- Changed the color of the font according to each section
- Changed the button styles (Subscription, more, share, and thumbs up/down)
- Changed the views styling item. 

We are cloning the Youtube archive webpage WITHOUT any side margins.

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
### **Status: Approved.** ✅ 
****
### Hi Team. 😄 
****
Great Job 💯 👍  @santiagorodriguezbermudez , @Bismarck-GM  You correctly implemented all the specifications.
You can merge this branch and move onto the next project. 🎊 
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Pull request merged**
